# Busca as categorias
GET http://localhost:3000/categorias
Content-Type: application/json
###


# Inclui uma nova categoria
POST http://localhost:3000/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxLCJlbWFpbCI6ImZyYW4ub2xpdmVpcmFAc291dW5pLmNvbSIsImlhdCI6MTcxODI5MDcwMCwiZXhwIjoxNzE4ODk1NTAwfQ.wcWeaFzao1kwytDuGz_nlo1gbYFlV4Wd3-OajGBii6w

{
    "nome" : "Itens"
}
###