# Cadastra um Usuário
POST http://localhost:3000/usuarios/cadastro
Content-Type: application/json

{
    "email" : "mayque.oliveira@souuni.com",
    "password" : "senhaforte"
}

###

# Loga o usuário
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
    "email" : "mayque.oliveira@souuni.com",
    "password" : "senhaforte"
}
###